### ISSUE TITLE
Refactor UI

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/holistic-toolbox#1]
We should find a cool design and copy it

**Comment by andrewlew1s** [comment]
Started in #4.

**Comment by michaelfitzhavey** [comment]
Let's choose a design along with making our first tool and then update [the template](https://github.com/holistic-web/holistic-toolbox/tree/master/.project/templates/toolbox-ui) appropriately

**Comment by michaelfitzhavey** [comment]
This is in progress with our initial design in #6

**Comment by michaelfitzhavey** [comment]
We now have a fairly decent design. Let's close this until we have a clear idea of further improvements
