### ISSUE TITLE
Continuous Deployment

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/holistic-toolbox#10]
We want our apps to deploy when they are merged into master. This will be very useful especially as we grow our tool set.

**Comment by michaelfitzhavey** [comment]
## Objectives
- [ ] only trigger linting / tests (if we have them) on a project if it has changes since last commit on master
- [ ] block merging of PR if linting / tests fail
- [ ] if change is on master branch: if a project is deployable, deploy it
- [ ] if change is on master branch: if a project is publishable, publish it, then publish a commit to master that patches the version of the project to a higher version (without triggering a recursive publish look :smil

**Comment by michaelfitzhavey** [comment]
Doing a little investigations as to whether [github actions](https://github.com/features/actions) can solve this problem for us...

**Comment by michaelfitzhavey** [comment]
Looks like #52 will need to be merged in to test fully as the nature of testing this requires making changes to our master branch... I will make sure I'm careful when I do this.

## To be tested
- [ ] that linting works and blocks PRs merging
- [ ] that deploying a tool and updating it's version number works
- [ ] that publishing a package and updating it's version number works

**Comment by michaelfitzhavey** [comment]
Since it's looking really promising so far - if these tests pass as part of this issue I'd like to write a script that will upgrade the version of toolbox linting / toolbox layout used by all tools and our website automatically.

**Comment by michaelfitzhavey** [comment]
@andrewlew1s this should be ready to review I think. Try making a change to a tool!

**Comment by andrewlew1s** [comment]
This is very awesome

**Comment by michaelfitzhavey** [comment]
@andrewlew1s thanks! Can you try making a PR with this so we can test it out with someone's PR other than mine?

**Comment by michaelfitzhavey** [comment]
Bugs have been found and fixed with the creation of https://github.com/holistic-web/holistic-toolbox/issues/69
