### ISSUE TITLE
Better error messages for JSON Formatter

### ISSUE THREAD

**Issue by dewinterjack** [holistic-web/holistic-toolbox#18]
I clearly don't know my JSON very well and came into this error:

<img width="638" alt="Screenshot 2020-01-17 at 18 54 25" src="https://user-images.githubusercontent.com/17269242/72653824-cdc06780-395a-11ea-8cb6-65b8f635d34d.png">

I'd like a better error like 
Expecting 'STRING',  got 'undefined'
Also the character that has the error could have red highlight

**Comment by dewinterjack** [comment]
I plan to fix this myself

**Comment by michaelfitzhavey** [comment]
Sounds interesting, currently we're just bubbling up the errors we get from [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) (https://github.com/holistic-web/holistic-toolbox/blob/master/tools/json-formatter/src/components/JsonFormatter.vue#L104).

We're displaying that as an error message on screen directly, perhaps there is a better way to pass the JSON?

**Comment by michaelfitzhavey** [comment]
There is also a console error when an error is found as we are sending the Error object to the component instead of the error message

![image](https://user-images.githubusercontent.com/2746248/72657168-02ebaa80-3999-11ea-8884-bd0f8ee6e921.png)

**Comment by dewinterjack** [comment]
Thanks, I'll look into that too 👍

**Comment by dewinterjack** [comment]
Found this from a quick google: https://www.npmjs.com/package/json-parse-better-errors

**Comment by dewinterjack** [comment]
> Found this from a quick google: https://www.npmjs.com/package/json-parse-better-errors

I tried this it is a tiny bit better however I'd like it to say expected string. This may be overkill for my first PR so I think I may make my first contribution a red marker where the error is

**Comment by michaelfitzhavey** [comment]
Sounds good, I'll see about any quick wins we can get to improve the error message in the meantime and close down this issue afterwords

**Comment by michaelfitzhavey** [comment]
Errors now looks a little bit better (at least CSS wise, closing this down for now as error handling improvement is open in issue #19)

![image](https://user-images.githubusercontent.com/2746248/72668804-5a822880-3a22-11ea-8617-6f84ef9e4e68.png)
