### ISSUE TITLE
Research practicality of OCR feature

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/holistic-toolbox#2]
Let's do this!

**Comment by michaelfitzhavey** [comment]
Sweet, let's flesh out the idea here: https://github.com/holistic-web/holistic-toolbox/blob/master/.project/tool-ideas.md#ocr-text-extractor and get it made! Some initial questions we should answer are below:

1. How should we deploy the backend for this tool? Will it be cost effective?

2. What services do we want to make available in the initial tool?

3. Could we potentially have multiple front end tools using the same back end service (i.e. face detector)? If so, which?

**Comment by andrewlew1s** [comment]
pr #5 has been closed down for the time being

**Comment by michaelfitzhavey** [comment]
Does this issue have momentum? If not maybe let's throw it back onto the roadmap to keep the issues board clean
