### ISSUE TITLE
 Markdown Renderer: add reset button to its taskbar

### ISSUE THREAD

**Issue by kyliechung** [holistic-web/holistic-toolbox#47]
<img width="1280" alt="Screen Shot 2020-02-03 at 17 49 58" src="https://user-images.githubusercontent.com/45569851/73643578-b7324400-46ae-11ea-94cb-93645996912e.png">

**Comment by michaelfitzhavey** [comment]
In progress in #48

**Comment by michaelfitzhavey** [comment]
This is added and live, thanks for the improvement, not sure how you made the design but nice one!
