### ISSUE TITLE
JSON Diff Tool

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/holistic-toolbox#54]
A useful tool to have would be the ability to get the diff between two JSON files / objects. 

This could be useful if a user has been editing a large JSON file and wants to check it against the original to check they've made the desired changes.

It can highlight differences like number of items in arrays etc.

**Comment by michaelfitzhavey** [comment]
This is in progress in #71

**Comment by michaelfitzhavey** [comment]
Ready to go, can go live after review

**Comment by dan47bennett** [comment]
This has been reviewed and merged.
