### ISSUE TITLE
Sprint 11/01/20

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/holistic-toolbox#7]
We aim to achieve the following core goals:

- [x] get JSON formatter into a functional state and merge #6 into the master branch

- [x] publish JSON formatter online. This should be under a subdomain i.e. `holistic-toolbox.web.app/json-fomatter` or `json-formatter.holisitc-toolbox.web.app`

- [x] refactor core UI components such as `tool-layout`, `button`, `header` into an npm library so that we can re use this code in other projects

- [ ] add basic adverts to the site

**Comment by andrewlew1s** [comment]
Research on part 2:

Firebase domains and sub-domains guide:
https://medium.com/@fransandi/use-firebase-multisite-hosting-to-associate-multiple-domains-subdomains-to-your-project-ee099109bfe9

**Comment by andrewlew1s** [comment]
Part 4 Ads Update:

We have attached Google Adsense to the site, and it is currently under review. If we receive good news and ads are approved, then we will have to update the site to display the ads in a way we want. If unapproved, we will have to edit in a way to make Google approve it next time.

**Comment by michaelfitzhavey** [comment]
To get ads it seems we need a main website at http://holistic-toolbox.com. This is being tracked in issue #9

**Comment by michaelfitzhavey** [comment]
Closing this down as this sprint is completed - nice effort!
